### PR TITLE
feat: Add new uploadSourcesGlob option

### PR DESCRIPTION
**Pull request by belemaire**
Due to our RN monorepo like application structure, most of our application code ends up in some `node_modules` directories. 

That being said, we don't really want to upload all sources referenced in the source map (i.e use `uploadSources` option along with `uploadNodeModules`) as it ends up being quite a lot of files. 

Even without monorepo, some users might like to be able to selectively upload some `node_modules` but not all.

This PR adds a new `uploadSourcesGlob` option (programmatic only) to address this. 
This option value can be an array of one or more glob strings, matching paths of sources files to upload. If this option is not provided, it will be set to a value that match the current behavior of `uploadSources` with and without `uploadNodeModules` set.

### CODE REVIEW

**Comment by xljones** [comment]
Hey again @belemaire, thanks for this PR. As with PR #53, we'll need to do some work on this to review the changes, and see what other updates we'll need to make if we integrate this. We won't be able to schedule for a while due to some of our other priorities.

I've raised this on our backlog to take a look at when time permits. For now you could fork the repository to start using your fix. Thanks again --Xander

**Comment by bengourley** [comment]
> That being said, we don't really want to upload all sources referenced in the source map (i.e use uploadSources option along with uploadNodeModules) as it ends up being quite a lot of files.

What's your concern regarding the number of files? Upload size? Upload speed? Unless you're coming up against a concrete issue here I'd simply recommend uploading everything. There is no size limit as far as Bugsnag is concerned.

I'd also recommend that you have whatever tool you're using to create the source maps include the sources too, since to have our tool go find them on disk is an extra lookup. For example, if you're using TypeScript this would be the `inlineSources` compiler option.

Let me know what you think of these approaches. Cheers!

**Comment by belemaire** [comment]
Hi @bengourley 
Thanks for your answer. 
For more context, we are using this tool for React Native applications.

It was indeed my intention to reduce the overall upload size, by only uploading the sources of the actual react native apps but not of their node modules.

But after giving more thoughts to it, your comment makes sense, i.e to just upload all the source files referenced in the source map. Anyway when sources are inlined inside the source map itself it's actually the whole sources referenced by the source maps.

We are using the upload sources feature for Hermes bundles only. For iOS the sources are inlined into the map itself (so actually all sources are included ... bouncing back on the fact that we can just upload all sources). But afaik the current way to compose the final source map when using Hermes (through [compose-source-maps.js](https://github.com/facebook/react-native/blob/master/scripts/compose-source-maps.js) script, does not support -yet- inlining the sources in the map that's why we have to rely on uploading sources. 
Just a quick follow up question on this as you might have more insights. Do you know why this script does not support inlining the sources ? Is that because of a complex technical challenge to do so (not sure because the `sources` field of the resulting source map is properly populated with all the files referenced in the source map so I feel it might be easy to just read the files and inline them accordingly, but I am not a source map expert, there might be other complexities to it), or is it just because it was not an immediate need. That's more a question for the RN core team but just wandering if you maybe have more context on this. 

I think this PR can be closed then, thanks again for feedback !

**Comment by bengourley** [comment]
Ah yes we noticed that too and opened a ticket on the Hermes/React Native repo: https://github.com/facebook/react-native/issues/26086

I don't know why it wasn't implemented in the first place, but the maintainers seem to accept it's something it can and should do – it just looks like they just haven't got round to it yet.

If you comment over there, perhaps it will climb their priority list!

Cheers

**Comment by belemaire** [comment]
Thanks @bengourley  :+1:

**Pull request closed without merging**
