### PR TITLE
added support for custom upload url

### PR DESCRIPTION
**Pull request by moebiusmania**
Hi, I've found your module very useful but since I'm working with Bugsnag Enterprise version, which is installed on-premise on internal servers in my company, I need it to have custom upload urls support. 

Since it was a small effort I have done it by myself and as you can see it's just few changes and keeps the code backward compatible.

Hope you will appreciate, thanks for sharing this!

### CODE REVIEW

**Comment by jmshal** [comment]
Thank you very much for your contribution, @moebiusmania. Having support for Bugsnag Enterprise is super important to me - it must have completely slipped my mind 😝 .

**Comment by jmshal** [comment]
Firstly thank you for the PR. I do have a couple of suggestions which I am happy to branch off your fork to make, but if you want to make them, that would be great too.

I feel that it may be worth making the third argument another object containing the upload *settings*. My only reason for this is so that if any more of these optional settings are needed in the future, we don't end up with a number of *optional* parameters.

```js
await upload({
  apiKey: 'xxx',
  // ...
}, {
  endpoint: 'https://bugsnag.local',
});
```

It's also worth probably making the `callback` argument optional as long as the `settings` argument is passed in.

I also thought about maybe re-using the `options` object for this purpose, but it would require some additional changes to make sure that we're not sending data over to the endpoint which doesn't need to be.

Once again, thank you. And please let me know if you want to make these adjustments yourself, otherwise I will happily merge this through and make them before the next release.

✌️

**Comment by moebiusmania** [comment]
It makes sense to have this functionality built better, but for the next day I won't be able to work on it so feel free to make the change.
Thanks

**Comment by jmshal** [comment]
Thanks @moebiusmania, I appreciate the time you have put into this.

**Comment by moebiusmania** [comment]
good work mate! can you please update the package on the NPM registry too?
thanks

**Comment by jmshal** [comment]
It should already be updated - available as "0.0.7".

**Comment by moebiusmania** [comment]
on NPM registry I still see this 😟  

screen shot 2017-03-30 at 11 04 23

**Comment by jmshal** [comment]
Oh my bad. Sorry @moebiusmania, I renamed the package a while ago, and at that time was unable to delete the old one from the registry. I need to get that sorted asap, to prevent this coming up again.

https://www.npmjs.com/package/bugsnag-sourcemaps

**Pull request merged**
